name: Scapy unit tests (manual) / utscapy

on:
  # Inspired from https://graphite.dev/guides/manually-trigger-github-actions.
  workflow_dispatch:
    inputs:
      os:
        description: "OS"
        required: true
        default: "ubuntu-latest"
      python:
        description: "Python version"
        required: true
        default: "3.8"
      mode:
        description: "Root / non-root"
        required: true
        default: "non_root"
      installmode:
        description: "Installation mode"
        required: true
        default: ""
      flags:
        description: "UT flags"
        required: true
        default: " -K scanner"

# Copied from 'unittests.yml'.
# See:
# - https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
# - https://docs.github.com/en/actions/how-tos/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read

jobs:
  utscapy:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Display inputs
        run: echo "os=${{ github.event.inputs.os }}" && echo "python=${{ github.event.inputs.python }}" && echo "mode=${{ github.event.inputs.mode }}" && echo "installmode=${{ github.event.inputs.installmode }}" && echo "flags=${{ github.event.inputs.flags }}"
      - name: Checkout Scapy
        uses: actions/checkout@v4
        # Codecov requires a fetch-depth > 1
        with:
          fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python }}
      - name: Install Tox and any other packages (linux/osx)
        run: ./.config/ci/install.sh ${{ github.event.inputs.installmode }}
        if: ${{ ! contains(github.event.inputs.os, 'windows') }}
      - name: Install Tox and any other packages (win)
        run: ./.config/ci/install.ps1
        if: ${{ contains(github.event.inputs.os, 'windows') }}
      - name: Run Tox (linux/osx)
        run: ./.config/ci/test.sh ${{ github.event.inputs.python }} ${{ github.event.inputs.mode }}
        env:
          UT_FLAGS: ${{ github.event.inputs.flags }}
        if: ${{ ! contains(github.event.inputs.os, 'windows') }}
      - name: Run Tox (win)
        run: ./.config/ci/test.ps1 ${{ github.event.inputs.python }}
        env:
          UT_FLAGS: ${{ github.event.inputs.flags }}
        if: ${{ contains(github.event.inputs.os, 'windows') }}
      # - name: Codecov
      #   uses: codecov/codecov-action@v5
      #   continue-on-error: true
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
